### PR TITLE
golang updates

### PR DESCRIPTION
**Pull request by joedugdale**
no longer built so had to make a couple of updates

### CODE REVIEW

**Comment by otakup0pe** [comment]
Huh. Do you have build errors handy or anything about your environment? And did it fail since the last time we merged into master (late April)

**Comment by joedugdale** [comment]
HI Jonathan
Was trying to build this on alpine linux container ( similar tp martinbaillie pull request) and hit this error- 

# github.com/imgix/prometheus-am-executor
./main.go:172:26: undefined: prometheus.Handler

see also 12th July - https://github.com/prometheus/client_golang/commit/761a2ff07c763475bff727730e823a8f4d501f36#diff-766cbb1abae0590229fc7bd36d56bda1

**Comment by pgporada** [comment]
The same sort of change had to be made on other prometheus exporters too such as https://github.com/kumina/unbound_exporter/pull/13/commits/9dcc0d06e7e326dcb4ce114cd4a79613e60e4b6a

**Comment by colakong** [comment]
@joedugdale thanks for the PR. Changes you proposed have finally been merged :hourglass:

**Pull request closed without merging**
